version: "3.8"

services:
    webserver:
        build:
            context: ./webserver
            dockerfile: Dockerfile
        command: python3 -m http.server
        volumes:
            - "ch1:/www/hls/ch1"
            - "ch2:/www/hls/ch2"
            - "ch3:/www/hls/ch3"
            - "ch4:/www/hls/ch4"
            - "./webserver/www-root:/www/"
        ports:
            - "8000:8000"

    encoder_ch1:
        build:
            context: ./encoder
            dockerfile: Dockerfile
        volumes:
            - "ch1:/rtsp/hls/"
        command: rtsp://${RTSP_USERNAME}:${RTSP_PASSWORD}@${RTSP_IP}:${RTSP_PORT}/ch1/0 ch1
    encoder_ch2:
        build:
            context: ./encoder
            dockerfile: Dockerfile
        volumes:
            - "ch2:/rtsp/hls/"
        command: rtsp://${RTSP_USERNAME}:${RTSP_PASSWORD}@${RTSP_IP}:${RTSP_PORT}/ch2/0 ch2
    encoder_ch3:
        build:
            context: ./encoder
            dockerfile: Dockerfile
        volumes:
            - "ch3:/rtsp/hls/"
        command: rtsp://${RTSP_USERNAME}:${RTSP_PASSWORD}@${RTSP_IP}:${RTSP_PORT}/ch3/0 ch3
    encoder_ch4:
        build:
            context: ./encoder
            dockerfile: Dockerfile
        volumes:
            - "ch4:/rtsp/hls/"
        command: rtsp://${RTSP_USERNAME}:${RTSP_PASSWORD}@${RTSP_IP}:${RTSP_PORT}/ch4/0 ch4
volumes:
    ch1:
    ch2:
    ch3:
    ch4:
